<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_CATEGORIES_card-img-top img-fluid</name>
   <tag></tag>
   <elementGuidId>1962e598-ce06-47bb-b81e-2bd73e298ae2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tbodyid']/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top.img-fluid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>448978f9-6747-4fbd-88ea-51aa7315c384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top img-fluid</value>
      <webElementGuid>831ecbee-6239-494e-92d8-d512fbd1a6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>imgs/galaxy_s6.jpg</value>
      <webElementGuid>3b514a0d-5b14-4137-aa8b-98ad55cabd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbodyid&quot;)/div[@class=&quot;col-lg-4 col-md-6 mb-4&quot;]/div[@class=&quot;card h-100&quot;]/a[1]/img[@class=&quot;card-img-top img-fluid&quot;]</value>
      <webElementGuid>79c43707-4c87-4042-8193-7fe9a1a160e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbodyid']/div/div/a/img</value>
      <webElementGuid>b0ff6ebc-fed1-4c68-935a-851ce6559074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>837ccfc0-3420-462f-9eee-d8df7724b8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'imgs/galaxy_s6.jpg']</value>
      <webElementGuid>7b2ee4be-2725-46fc-bfd1-220b8b966830</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
